# fly.toml app configuration file generated for encurso on 2023-09-22T21:38:08-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "encurso"
primary_region = "gdl"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
