# fly.toml app configuration file generated for vim on 2023-08-05T16:57:14-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vim"
primary_region = "qro"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
